#!/bin/sh

############################################################################
# phi CLI for Linux
############################################################################

if test -z "$PHP_COMMAND"
then
  PHP_COMMAND=php
fi

if test -z "$PHI_HOME"
then
  PHI_HOME=$(cd $(dirname $0)/..;pwd)
fi

$PHP_COMMAND -d html_errors=off "$PHI_HOME/command/phi.php" $@
