date:
  class: PHI_DateHelper

form:
  class: PHI_FormHelper
  containErrors: 正しく入力されていない項目があります。(残り\1箇所)

html:
  class: PHI_HTMLHelper

pager:
  class: PHI_PagerHelper
  bind: FALSE
  nextLabel: 次へ
  previousLabel: 前へ
  navigationLabel: '\1-\2 件表示 / \3 件中 \4 \5<br />\6'
  ascendingLabel: '<img src="/assets/base/phi/images/sort_asc.png" width="7" height="7" class="sort-asc" alt="昇順に並び替え" />'
  descendingLabel: '<img src="/assets/base/phi/images/sort_desc.png" width="7" height="7" class="sort-desc" alt="降順に並び替え" />'

site:
  class: PHI_SiteHelper

request:
  class: PHI_RequestHelper

user:
  class: PHI_UserHelper

