rewriteTestRoute:
  uri: /rewriteTest
  forward:
    module: entry
    action: Index

cpanelConnectTestRoute:
  uri: /cpanel/connectTest
  forward:
    module: cpanel
    action: ConnectTest

defaultModuleRoute:
  uri: /:action
  forward:
    module: "{%MODULE.ENTRY%}"

moduleRoute:
  uri: /:module/:action

cpanelRoute:
  uri: /cpanel/
  forward:
    module: cpanel
    action: LoginForm

defaultRoute:
  uri: /
  forward:
    module: "{%MODULE.ENTRY%}"
    action: Index

